### ISSUE TITLE
Running OpenDroneMap on HPC

### ISSUE THREAD

**Issue by quannguyen02** [OpenDroneMap/ClusterODM#100]
**Purposes:**
1a. Implement rootless container to run ODM on HPC, using Singularity (for ODM) and Podman (NodeODM)
1b. Use binary files if could not proceed with 1a
2. Connect ClusterODM to NodeODM in HPC environment, probably with proxy.
3. Use SLURM to dynamically assign tasks between different nodes in NodeODM.

**Comment by nghi01** [comment]
We've decided to use Apptainer as the rootless alternative to Docker. We don't really need to use apptainer to run the container since we'll still be using Docker container for ClusterODM. Most of our problems are resolved when building Apptainer container for NodeODM to run on HPC. We will add documentation about this

**Comment by nghi01** [comment]
This issue should be solved by the latest updates of Apptainer related-pull-request. We will be doing further testing and add documentation and script example about SLURM to better approach the running ODM on HPC.
