### ISSUE TITLE
Docker image versions are not pushed to Dockerhub

### ISSUE THREAD

**Issue by FJEANNOT** [OpenDroneMap/ClusterODM#94]
### What is the problem?

On Dockerhub, the only tags available are `latest` and `master`. https://hub.docker.com/r/opendronemap/clusterodm/tags
This is against best practice as new versions can break existing environments. Docker users are advised to not use the `latest` tag to avoid unwanted updates.

**Comment by PhearZero** [comment]
It looks like @pierotofy added tags to the CI about 5 months ago but there has not been any tagged releases since then. It would be possible to checkout each tagged commit and manually build/push the older images. 

https://github.com/OpenDroneMap/ClusterODM/blame/master/.github/workflows/publish-docker.yml#L8

**Comment by pierotofy** [comment]
Chiming in (sorry for the late reply); we keep ClusterODM on a rolling release like the rest of the ecosystem and docker hub will automatically remove images that don't get pulls after a while.

It's easy for somebody to pin to an older version (or stick to a stable version) if they need to: they can re-tag the image and push it to a separate repo, then reference that.
